### ISSUE TITLE
Development support

### ISSUE THREAD

**Issue by jbadeau** [joswarmer/ProjectIt#2]
Hi,

I have been interested in building a react based projectional editor for some time. Would you mind some development support.

I have forked and will be adding:

- replace ts projects with real npm modules using lerna
  e.g. @projectit/core, @projectit/meta ...
- Replace docs (MDX) with GatsbyJS and MDX for site an documentation
- exchange sass for typestyle
- make the ui more usable

please let me know if this sounds good and what you would like to do.

**Comment by joswarmer** [comment]
Hi Jose,

I just got back from a holiday and found your issue. Thanks for your interest in ProjectIt. I am interested why you have been interested in building a projectional editor. It's not everybody's cup of cake.

To answer your first question: yes, I do welcome development support. As you can see, there is enough work to be done. 

* Replacing the ts projects with real publishable npm modules is going to be _very_ useful. It is one of tghe todo's on my list. I did have had a quick look at Lerna and yarn workspaces, but not enough to make a choice. So a setup with Lerna would be very helpfull.

* I have already started the documentation site using Asciidoc and Antora.  I have used Asciidoc for other projects as well and am very happy with it. I don't know MDX  or GatsbyJS, at first sight it looks like quite a different approach. I like to stick with Asciidoc/Antora. See [antora.org](https://docs.antora.org) and e.g.  [https://docs.couchbase.com/server/6.0/introduction/intro.html](https://docs.couchbase.com/server/6.0/introduction/intro.html) for examples.

* I was not aware of typestyle, but I have taken a look at it. It looks like an very nice way to get typed CSS inside your typescript code. It seems a good idea to start using typestyle instead of sass. I have one question however, will it be possible for users of ProjectIt to use plain CSS (or SASS) to add styles to the boxes,  or do they have to use typestyle as well? It would be best of they have both options.

* Making the UI more usable is probably the key area for ProjectIt to improve. It sounds easier that it is in many cases, as there are no clear rules for usability of a projectional editor. In my experience this needs quite some experimentation. I am interested in your ideas of how to improve this.

**Comment by jbadeau** [comment]
Hi Jos,

The reason I would like a web based projectional editor is because I often have the need to mix grammars which is hard to do with parsers.

For example:
```
Given <user> is authenticated
* (user) => authSrv.login(user)
```
Line 1 is a free text grammar with placeholder <user>
Line 2 is scripting grammar which uses the placeholder

1. Lerna and yarn workspaces are complimentary so you don't need to choose. I have modularized everything except for the demo app. I will checkin sometime this week.

2. MDX is markdown but with the ability to embedded react components. It is pretty similar to asciidoc but with a much much larger community.

3. Typestyle or any CSS in JS solution does not force one to use it but it's easier.

4. This is where I can help allot but I think the first point should be clear first.

Maybe we could do a skype session this week to go over a few things.?

Jose

**Comment by jbadeau** [comment]
I checked in the monorepo branch https://github.com/jbadeau/ProjectIt. I need to add the tests back and the docs but the modularization is done.

should be able to complete by our thursday chat.

**Comment by jbadeau** [comment]
I have added the docs project so u can see the markdown work flow in action. It is very very close to the asciidoc workflow.

**Comment by jbadeau** [comment]
What time would be good? What about in the evening around 7? I’m gmt+2.

**Comment by joswarmer** [comment]
You mean 7 pm CET?
That is fine with me.
Will send you my Skype ID tomorrow.

Where are you based?

Jos Warmer

Sent from BlueMail<http://www.bluemail.me/r?b=14726> On 8 May 2019, at 21:44, Jose Badeau <notifications@github.com<mailto:notifications@github.com>> wrote:

What time would be good? What about in the evening around 7? I’m gmt+2.

**Comment by jbadeau** [comment]
Sorry. 7PM. I am based in Zurich Switzerland but I am from the US.

**Comment by joswarmer** [comment]
Tried the monorepo, and running `yarn start` in the demo module, but are getting errors "Cannot find module @projectit/core", for all modules. I might have forgotten something regarding lerna, but do you have some instructions on how to run the demo?

**Comment by jbadeau** [comment]
Hi please sync again. There is a conflict with the hot-module-loader between the demo and the docz. I will fix this tonight.

**Comment by jbadeau** [comment]
yarn
then yarn start is enough

**Comment by joswarmer** [comment]
It seems I first have to manually compile all packages before yarn start (in the demo dir) starts working.
Also, my IDE (WebStorm) still cannot find the modules, and therefore becomes more or less unusable.

**Comment by jbadeau** [comment]
Very strange. Please delete the node_modules folder and the yarn lock file.
Otherwise let’s have a look tonight.

**Comment by jbadeau** [comment]
Just saw that the yarn lock was excluded global from git. So never committed.

**Comment by jbadeau** [comment]
So I just pushed. If something is wrong still let’s look tonight. Not to waste your time

**Comment by joswarmer** [comment]
I have other problems, like my IDE
- will not refactor across modules anymore, 
- find usages also finds usages in generated JS
- import references sometimes go to .d.ts files instead of the actual source.
- multiple errors in @types/... modules which compiling 
- etc.
This is a crucial issue, I definitively need to be able to use WebStorm with the project setup.

**Comment by jbadeau** [comment]
Hi my tram was late so I’ll be on at 7:15. Sorry about the delay

**Comment by jbadeau** [comment]
closing and opening smaller issues
